project:
  type: website

website:
  title: ""
  sidebar:
    style: "docked"
    search: false
    contents:
      - text: ""

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



